CREATE DATABASE ONLINE_SHOP
DROP DATABASE ONLINE_SHOP

USE ONLINE_SHOP

CREATE TABLE ADDRESS
(
ADDRESS_ID INT IDENTITY(1,1) PRIMARY KEY ,
COUNTRY_NAME VARCHAR(40) NOT NULL,
TOWN_NAME VARCHAR(40) NOT NULL,
ZIP_CODE VARCHAR(10) NOT NULL,
ADDRESS_NAME VARCHAR(40) NOT NULL,
ADDRESS_NUMBER TINYINT NOT NULL
)

CREATE TABLE CLIENT
(
CLIENT_ID INT IDENTITY(1,1) PRIMARY KEY,
EMAIL VARCHAR(30) NOT NULL UNIQUE,
USERNAME VARCHAR(20) NOT NULL UNIQUE,
PASSWORD VARCHAR(20) NOT NULL,
FIRST_NAME VARCHAR(10) NOT NULL,
LAST_NAME VARCHAR(10) NOT NULL,
PHONE_NUMBER VARCHAR(10) NOT NULL,
IS_BLOCKED BIT CHECK (IS_BLOCKED IS NOT NULL),
DEFAULT_ADDRESS INT FOREIGN KEY REFERENCES ADDRESS(ADDRESS_ID) UNIQUE
)

CREATE TABLE CLIENTS_ADDRESSES
(
ID INT IDENTITY(1,1) PRIMARY KEY,
CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID),
ADDRESS_ID INT FOREIGN KEY REFERENCES ADDRESS(ADDRESS_ID)
)


SELECT * FROM ADDRESS

INSERT INTO ADDRESS
VALUES ('Bulgaria','Plovdiv','4220','Dunav',3),
       ('Bulgaria','Sofia','5692','Petur Beron',6),
	   ('Bulgaria','Veliko Turnovo','1212','Preslav',14),
	   ('Bulgaria','Haskovo','3541','Izgrev',67),
	   ('Bulgaria','Pazardjik','9713','Struma',8),
	   ('Bulgaria','Kalofer','7341','Hristo Botev',10)

SELECT * FROM CLIENT



INSERT INTO CLIENT
VALUES ('scoobydoo@gmail.com','scooby','poslushnokuchence123','Nikolai','Petrov','0320120311',1,1),
       ('pancho@gmail.com','pancho','kazarma23','Pancho','Velkov','0320123131',0,2),
	   ('darinb@gmail.com','darinb','ghsdiahsofa','Darin','Borisov','0320187511',0,3),
	   ('georgiv@gmail.com','goshkov','goshkomoshko','Georgi','Videv','032012684',0,4),
	   ('hristina@gmail.com','dhrisi','hlsaldas1','Hristina','Petrova','0367677311',0,6),
	   ('kremena@gmail.com','kremenad','ghsdkljdlk','Kremena','Trifonova','0329867311',1,5)

SELECT * FROM CLIENTS_ADDRESSES

INSERT INTO CLIENTS_ADDRESSES
VALUES (3,6), 
       (3,5),
	   (3,4),
	   (4,3),
	   (5,2),
	   (6,2),
       (2,4),
	   (1,5)


CREATE TABLE STATUS
(
STATUS_ID INT IDENTITY(1,1) PRIMARY KEY,
STATUS_NAME VARCHAR(40) NOT NULL UNIQUE
)

SELECT * FROM STATUS

INSERT INTO STATUS 
VALUES ('Izpratena'),
       ('Neplatena'),
	   ('Odobreno plashtane'),
	   ('Podgotvena za izprashtane'),
	   ('Poluchena')

	

CREATE TABLE SPECIFICATION
(
SPEC_ID INT IDENTITY(1,1) PRIMARY KEY,
SPECIFICATION_NAME VARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE CATEGORY
(
CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
CATEGORY_NAME VARCHAR(30) NOT NULL UNIQUE,
BASE_CATEGORY INT FOREIGN KEY REFERENCES CATEGORY(CATEGORY_ID) DEFAULT (NULL)
)

DROP TABLE CATEGORY
TRUNCATE TABLE CATEGORY

SELECT * FROM CATEGORY

INSERT INTO CATEGORY
VALUES ('MODA', DEFAULT),
       ('MUJE', 1),
	   ('JENI', 1),
	   ('DECA', 1),
	   ('BIJUTA',3 ),
	   ('PORFEILI',2),
	   ('DETSKI RANICI', 4),
	   ('SWAROVSKI', 5 ),
	   ('KOJENI', 6)

SELECT * FROM SPECIFICATION

INSERT INTO SPECIFICATION
VALUES ('CVQT'),
       ('RAZMER'),
	   ('GARANCIQ'),
	   ('MATERIQ'),
	   ('DETAILI'),
	   ('PROIZHOD')

INSERT INTO CATEGORY
VALUES ('HRANITELNI PRODUKTI',DEFAULT),
       ('ZELENCHUCI',10),
       ('PLODOVE',10)

CREATE TABLE CATEGORIES_SPECS
(
ID INT PRIMARY KEY IDENTITY(1,1),
CATEGORY_ID INT FOREIGN KEY REFERENCES CATEGORY(CATEGORY_ID) NOT NULL,
SPEC_ID INT FOREIGN KEY REFERENCES SPECIFICATION(SPEC_ID) NOT NULL
)


SELECT * FROM CATEGORY
SELECT * FROM SPECIFICATION
SELECT * FROM CATEGORIES_SPECS

INSERT INTO CATEGORIES_SPECS
VALUES (5,1),
       (5,5),
	   (5,3),
	   (5,2),
	   (7,4),
	   (7,5),
	   (11,6),
	   (12,6)

CREATE TABLE PRODUCT
(
PRODUCT_ID INT IDENTITY(1,1) PRIMARY KEY,
PRODUCT_NAME VARCHAR(30) NOT NULL UNIQUE,
DELIVERY_PRICE SMALLMONEY NOT NULL,
SALE_PRICE SMALLMONEY NOT NULL,
CATEGORY_ID INT FOREIGN KEY REFERENCES CATEGORY(CATEGORY_ID) NOT NULL
)

INSERT INTO PRODUCT
VALUES ('CHERESHI',5.20, 6.20, 12),
       ('KRASTAVICI',3.50, 4.10, 11),
	   ('PRASKOVI',2.20, 4.20, 12),
	   ('DOMATKI',3.20, 6.50, 11)

SELECT * FROM PRODUCT
DROP TABLE PRODUCTS_SPECS

CREATE TABLE PRODUCTS_SPECS
(
ID INT IDENTITY(1,1) PRIMARY KEY,
PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID) NOT NULL,
SPECS_ID INT FOREIGN KEY REFERENCES SPECIFICATION(SPEC_ID) NOT NULL,
SPECIFICATION_VALUE VARCHAR(20) NOT NULL
)

SELECT * FROM CATEGORIES_SPECS
SELECT * FROM PRODUCTS_SPECS
SELECT * FROM SPECIFICATION

INSERT INTO PRODUCT
VALUES ('GRIVNICHKA', 56.20, 102.99, 5)

INSERT INTO PRODUCTS_SPECS
VALUES (1,6,'TURCIQ'), 
       (2,6, 'POLSHA'),
	   (3,6, 'GURCIQ'),
	   (4,6, 'BULGARIA'),
	   (5,5, 'FINNA IZRABOTKA'),
	   (5,3, '12 MESECA'),
	   (5,2, 'WRIST-M')


	  -------------------
SELECT PRODUCT_NAME, CATEGORY_ID, SPECIFICATION_NAME, SPECIFICATION_VALUE 
FROM PRODUCTS_SPECS PS  JOIN PRODUCT P ON P.PRODUCT_ID = PS.PRODUCT_ID
                JOIN SPECIFICATION S ON S.SPEC_ID = PS.SPECS_ID


CREATE TABLE ORDERS
(
ID INT IDENTITY(1,1) PRIMARY KEY,
ORDER_NUMBER VARCHAR(10) NOT NULL,
DATE_TIME DATETIME DEFAULT GETDATE() NOT NULL,
STATUS_ID INT FOREIGN KEY REFERENCES STATUS(STATUS_ID) NOT NULL,
CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID) NOT NULL,
PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID) NOT NULL ,
QUANTITY INT NOT NULL
)

SELECT * FROM ORDERS
TRUNCATE TABLE ORDERS

INSERT INTO ORDERS
VALUES ('000001',DEFAULT,1,1,1,5),
       ('000002',DEFAULT,2,4,2,1),
       ('000003',DEFAULT,3,3,3,3),
       ('000004',DEFAULT,4,2,4,2),
       ('000005',DEFAULT,3,3,5,4),
       ('000006',DEFAULT,5,4,1,5)


CREATE TABLE CLIENTS_ORDERS
(
ID INT IDENTITY(1,1) PRIMARY KEY,
CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID) NOT NULL,
ORDER_ID INT FOREIGN KEY REFERENCES ORDERS(ID) NOT NULL
)

INSERT INTO CLIENTS_ORDERS
VALUES (1,3),
       (1,5),
	   (4,4),
	   (3,6)

SELECT * FROM CLIENTS_ORDERS





	  
	  




   